// PRORESMAT control centre: Overview • Approvals • Care • Finance • Risk
import { route, S, go, api, toast, sheet, confirmSheet, refresh, closeSheets, signOut } from '../app.js';
import { regLabel, html, raw, icon, money, fmtDate, fmtDateTime, cap, words, avatar, packArt, status, classBadge, empty, kv, section, tabs, field, input, textarea, select, check, when } from '../ui.js';

const has = (...r) => S.user.roles.some((x) => r.includes(x));
const reasonAction = (apiName, idKey = 'id') => async (d) => {
  const danger = /suspend|deactivate|recall|reject/.test(d.action);
  const r = await confirmSheet({ title: `${cap(d.action)}?`, body: d.body || '', confirmLabel: cap(d.action), danger, reason: d.action !== 'start_review' });
  if (!r.ok) return;
  await api(apiName, { [idKey]: d.id, action: d.action, reason: r.reason || 'Review started' });
  toast('Done. Recorded in the audit log.');
  closeSheets();
  refresh();
};

route('/a/overview', async (ctx) => {
  ctx.title = 'Overview';
  ctx.wide = true;
  const o = await api('admin.overview');
  ctx.act('logout', () => signOut());
  const tile = (n, label, href, tone = '') => html`<button type="button" class="kpi ${tone}" data-go="${href}"><strong>${n}</strong><span>${label}</span></button>`;
  return html`
    <div class="row between"><p class="muted small">Signed in as ${S.user.name} · ${S.user.roles.map(cap).join(', ')}</p><button class="btn small ghost" data-act="logout">${icon('logout')} Sign out</button></div>
    ${when(has('admin'), () => section('Approvals waiting', html`<div class="kpis">${tile(o.approvals.practitioners, 'Practitioners', '#/a/approvals?tab=practitioners', o.approvals.practitioners ? 'warn' : '')}${tile(o.approvals.orgs, 'Clinics & pharmacies', '#/a/approvals?tab=orgs', o.approvals.orgs ? 'warn' : '')}${tile(o.approvals.products, 'Product listings', '#/a/approvals?tab=products', o.approvals.products ? 'warn' : '')}${tile(o.approvals.reviews, 'Reviews to moderate', '#/a/care?tab=reviews')}</div>`))}
    ${when(has('admin', 'support'), () => section('Care & safety', html`<div class="kpis">${tile(o.care.urgent, 'Urgent follow-ups', '#/a/care', o.care.urgent ? 'bad' : '')}${tile(o.care.open, 'Open care queue', '#/a/care')}${tile(o.care.adverse, 'Adverse events', '#/a/care?tab=adverse', o.care.adverse ? 'warn' : '')}${tile(o.care.complaints, 'Open complaints', '#/a/care?tab=tickets')}${tile(o.care.privacy, 'Privacy requests', '#/a/care?tab=privacy')}</div>`))}
    ${when(has('admin', 'finance'), () => section('Finance', html`<div class="kpis">${tile(money(o.finance.collected), `Collected (${o.finance.payments} payments)`, '#/a/finance')}${tile(money(o.finance.refunded), 'Refunded', '#/a/finance?tab=refunds')}${tile(money(o.finance.revenue), 'PRORESMAT revenue', '#/a/finance?tab=ledger')}${tile(money(o.finance.eligible), 'Ready to settle', '#/a/finance?tab=settlements', o.finance.eligible ? 'ok' : '')}${tile(money(o.finance.onHold), 'Settlement on hold', '#/a/finance?tab=settlements')}${tile(o.finance.disputes, 'Open disputes', '#/a/finance?tab=disputes', o.finance.disputes ? 'bad' : '')}</div>`))}
    ${when(has('admin'), () => section('Risk', html`<div class="kpis">${tile(o.risk.expiringPractitioners, 'Licences expiring ≤30 days', '#/a/risk?tab=expiring', o.risk.expiringPractitioners ? 'warn' : '')}${tile(o.risk.expiringProducts, 'FDA registrations expiring', '#/a/risk?tab=expiring')}${tile(o.risk.failedLogins24h, 'Failed sign-ins (24 h)', '#/a/risk?tab=security')}</div>`))}
    ${section('Platform', kv([['Active customers', o.counts.customers], ['Bookable practitioners', o.counts.activePractitioners], ['Products on sale', o.counts.liveProducts], ['Consultations', o.counts.bookings], ['Orders', o.counts.orders]]))}
    ${when(has('admin'), () => section('Recent activity', auditList(o.activity)))}
    ${when(S.meta.demo, () => html`<button class="btn ghost" data-go="#/demo">Test tools (clock, outbox, reset)</button>`)}`;
}, { auth: true, wide: true });

const auditList = (rows) => html`<div class="table-wrap"><table class="tbl small"><thead><tr><th>When</th><th>Who</th><th>Action</th><th>Record</th><th>Change</th><th>Reason</th></tr></thead><tbody>${rows.map((a) => html`<tr><td>${fmtDateTime(a.at)}</td><td>${a.actorName}</td><td class="mono">${a.action}</td><td class="mono">${a.entity}/${a.entityId.slice(-6)}</td><td class="small">${a.before ? html`<span class="muted">${JSON.stringify(a.before).slice(0, 60)}</span> → ` : ''}${a.after ? JSON.stringify(a.after).slice(0, 80) : ''}</td><td>${a.reason}</td></tr>`)}</tbody></table></div>`;

// ---------- approvals ----------
route('/a/approvals', async (ctx) => {
  ctx.title = 'Approvals';
  ctx.wide = true;
  const tab = ctx.query.tab || 'practitioners';
  const r = await api('admin.approvals');
  ctx.act('tab', (d) => go('#/a/approvals?tab=' + d.v));
  ctx.act('prac', reasonAction('admin.setPractitionerStatus'));
  ctx.act('org', reasonAction('admin.setOrgStatus'));
  ctx.act('prod', reasonAction('admin.setProductStatus'));
  ctx.act('approvePrac', (d) => {
    const p = r.practitioners.find((x) => x.id === d.id);
    sheet(`Approve ${p.fullName}`, html`<form class="stack" data-form="approvePrac"><input type="hidden" name="id" value="${p.id}"><input type="hidden" name="action" value="${d.mode || 'approve'}">
      ${field('Provider class', select('providerClass', [['independent', 'Verified independent'], ['supervised', 'PRORESMAT-supervised']], p.providerClass))}
      ${field('Supervisor (required for supervised)', select('supervisorId', r.supervisors.filter((s) => s.id !== p.id).map((s) => [s.id, s.fullName]), p.supervisorId || '', { blank: 'None' }))}
      ${when(['MDC', 'PC'].includes(p.council), () => check('canPrescribe', 'Registered scope includes prescriptions', p.canPrescribe))}
      ${when(d.mode === 'update_supervision', () => check('isSupervisor', 'Can supervise other practitioners', p.isSupervisor))}
      ${field('Verification note (audit log)', textarea('reason', { rows: 2, value: d.mode === 'update_supervision' ? '' : 'Identity, qualification, council registration, licence and facility licence verified.' }))}
      <p class="form-error" role="alert" hidden></p><button class="btn primary">${d.mode === 'update_supervision' ? 'Save' : 'Approve and publish'}</button></form>`);
  });
  ctx.form('approvePrac', async (v) => { await api('admin.setPractitionerStatus', { ...v, canPrescribe: v.canPrescribe === true }); closeSheets(); toast('Saved. Recorded in the audit log.'); refresh(); });
  ctx.act('viewPrac', (d) => {
    const p = r.practitioners.find((x) => x.id === d.id);
    sheet(p.fullName, html`<div class="stack"><div class="row">${avatar(p.avatar, 48, p.fullName)}<div><strong>${p.fullName}</strong><p class="small">${p.title} · ${p.email}</p>${status(p.status)} ${classBadge(p.providerClass, p.classLabel)}</div></div>
      ${kv([['Ghana Card', p.identity?.idNumber], ['Qualification', p.qualification], ['Council registration', regLabel(p.council, p.registrationNumber)], ['Licence expiry', fmtDate(p.licenceExpiry)], ['Facility', `${p.facility.name}, ${p.facility.address}`], ['Facility licence', `${p.facility.licenceNo} to ${fmtDate(p.facility.licenceExpiry)}`], ['Consultation types', p.modes.join(', ')], ['Fee', money(p.fee)], ['Settlement', p.settlement.method === 'bank' ? `${p.settlement.bankName} ${p.settlement.accountNumber}` : `${p.settlement.momoProvider} ${p.settlement.momoNumber}`], ['Agreements', p.agreements?.provider ? `Accepted ${fmtDate(p.agreements.provider)}` : 'Missing'], ['Evidence files', p.evidence], ['Supervisor', p.supervisorName || '—'], ['Pending renewal', p.pendingRenewal ? `to ${fmtDate(p.pendingRenewal.licenceExpiry)}` : '—']])}
      <div class="row wrap">
        ${when(['submitted', 'changes_required'].includes(p.status), () => html`<button class="btn primary" data-act="approvePrac" data-id="${p.id}">Approve</button><button class="btn ghost" data-act="prac" data-id="${p.id}" data-action="request_changes">Request changes</button>`)}
        ${when(p.status === 'active', () => html`<button class="btn ghost" data-act="approvePrac" data-id="${p.id}" data-mode="update_supervision">Class & supervision</button><button class="btn danger" data-act="prac" data-id="${p.id}" data-action="suspend">Suspend</button>`)}
        ${when(p.status === 'suspended', () => html`<button class="btn primary" data-act="prac" data-id="${p.id}" data-action="reactivate">Reactivate</button>`)}
        ${when(p.pendingRenewal, () => html`<button class="btn primary" data-act="prac" data-id="${p.id}" data-action="approve_renewal">Verify renewal</button><button class="btn ghost" data-act="prac" data-id="${p.id}" data-action="reject_renewal">Reject renewal</button>`)}
        ${when(p.status !== 'deactivated', () => html`<button class="btn ghost" data-act="prac" data-id="${p.id}" data-action="deactivate">Deactivate</button>`)}
      </div>
      ${section('History', html`<ol class="timeline">${p.statusHistory.map((h) => html`<li class="done"><span class="tl-dot" aria-hidden="true"></span><span><strong>${cap(h.action || h.status)}</strong> <span class="small muted">${fmtDateTime(h.at)} · ${h.by}</span><br><span class="small">${h.reason}</span></span></li>`)}</ol>`)}</div>`, { wide: true });
  });
  ctx.act('viewOrg', (d) => {
    const o = r.orgs.find((x) => x.id === d.id);
    sheet(o.name, html`<div class="stack"><p>${status(o.status)} <span class="badge line">${cap(o.type)}</span></p>
      ${kv([['Business registration', o.businessRegNo], ['TIN', o.taxId], ['Address', o.address], ['Phone', o.phone], ['Facility licence', `${o.facilityLicenceNo} to ${fmtDate(o.licenceExpiry)}`], o.superintendentPharmacist && ['Superintendent pharmacist', `${o.superintendentPharmacist} (${o.pharmacyCouncilLicence})`], ['Beneficial owner', o.beneficialOwner ? `${o.beneficialOwner.name}, ${o.beneficialOwner.idNumber}, ${o.beneficialOwner.ownershipPct}%` : '—'], ['Authorised representative', o.authorisedRep ? `${o.authorisedRep.name} (${o.authorisedRep.position})` : '—'], ['Settlement', o.settlement ? (o.settlement.method === 'bank' ? `${o.settlement.bankName} ${o.settlement.accountNumber}` : `${o.settlement.momoProvider} ${o.settlement.momoNumber}`) : '—'], ['Seller agreement', o.agreementAcceptedAt ? `Accepted ${fmtDate(o.agreementAcceptedAt)}` : 'Missing'], ['Refund terms', o.refundTerms], ['Pending renewal', o.pendingRenewal ? `to ${fmtDate(o.pendingRenewal.licenceExpiry)}` : '—']])}
      <div class="row wrap">
        ${when(['submitted', 'changes_required'].includes(o.status), () => html`<button class="btn primary" data-act="org" data-id="${o.id}" data-action="approve">Approve</button><button class="btn ghost" data-act="org" data-id="${o.id}" data-action="request_changes">Request changes</button>`)}
        ${when(o.status === 'active', () => html`<button class="btn danger" data-act="org" data-id="${o.id}" data-action="suspend">Suspend</button>`)}
        ${when(o.status === 'suspended', () => html`<button class="btn primary" data-act="org" data-id="${o.id}" data-action="reactivate">Reactivate</button>`)}
        ${when(o.pendingRenewal, () => html`<button class="btn primary" data-act="org" data-id="${o.id}" data-action="approve_renewal">Verify renewal</button>`)}
      </div></div>`, { wide: true });
  });
  ctx.act('viewProd', (d) => {
    const p = r.products.find((x) => x.id === d.id);
    const acts = { submitted: ['start_review', 'approve', 'request_changes'], under_review: ['approve', 'request_changes'], approved: ['suspend', 'recall', 'request_changes'], suspended: ['reinstate', 'recall', 'request_changes'], expired: ['recall'] }[p.status] || [];
    sheet(p.name, html`<div class="stack"><div class="row">${packArt(p.image, 56, p.name)}<div><p>${status(p.status)}</p><p class="small">${p.seller} · seller ${p.orgStatus}</p></div></div>
      ${kv([['FDA registration', `${p.fdaRegNo} to ${fmtDate(p.fdaExpiry)}`], ['Manufacturer', p.manufacturer], ['Ingredients', p.ingredients], ['Indication (claim)', p.indication], ['Directions', p.directions], ['Warnings', p.warnings], ['Contraindications', p.contraindications], ['Pregnancy', p.pregnancy], ['Interactions', p.interactions], ['Price / stock', `${money(p.price)} · ${p.stock}`], ['Batches supplied', (p.batches || []).map((b) => b.batch).join(', ') || '—']])}
      <p class="note">${icon('shield')} Check the FDA register entry, label and claims. Only "traditionally used for…" or registered indications are allowed.</p>
      <div class="row wrap">${acts.map((a) => html`<button class="btn ${a === 'approve' || a === 'reinstate' ? 'primary' : /recall|suspend/.test(a) ? 'danger' : 'ghost'}" data-act="prod" data-id="${p.id}" data-action="${a}">${cap(a)}</button>`)}</div>
      ${section('History', html`<ol class="timeline">${p.statusHistory.map((h) => html`<li class="done"><span class="tl-dot" aria-hidden="true"></span><span><strong>${cap(h.status)}</strong> <span class="small muted">${fmtDateTime(h.at)} · ${h.by}</span><br><span class="small">${h.reason}</span></span></li>`)}</ol>`)}</div>`, { wide: true });
  });
  const pending = { practitioners: r.practitioners.filter((p) => p.status === 'submitted' || p.pendingRenewal).length, orgs: r.orgs.filter((o) => o.status === 'submitted' || o.pendingRenewal).length, products: r.products.filter((p) => ['submitted', 'under_review'].includes(p.status)).length };
  const head = tabs([['practitioners', 'Practitioners', pending.practitioners], ['orgs', 'Clinics & pharmacies', pending.orgs], ['products', 'Products', pending.products]], tab);
  if (tab === 'orgs') return html`${head}<div class="table-wrap"><table class="tbl"><thead><tr><th>Organisation</th><th>Type</th><th>Licence to</th><th>Status</th><th></th></tr></thead><tbody>${r.orgs.map((o) => html`<tr><td><strong>${o.name}</strong><br><span class="small muted">${o.address}</span></td><td>${cap(o.type)}</td><td>${fmtDate(o.licenceExpiry)}</td><td>${status(o.status)}${o.pendingRenewal ? html`<br><span class="small warn-text">Renewal pending</span>` : ''}</td><td><button class="btn small ghost" data-act="viewOrg" data-id="${o.id}">Review</button></td></tr>`)}</tbody></table></div>`;
  if (tab === 'products') return html`${head}<div class="table-wrap"><table class="tbl"><thead><tr><th>Product</th><th>Seller</th><th>FDA expiry</th><th>Status</th><th>On sale</th><th></th></tr></thead><tbody>${r.products.sort((a, b) => (['submitted', 'under_review'].includes(a.status) ? -1 : 1) - (['submitted', 'under_review'].includes(b.status) ? -1 : 1)).map((p) => html`<tr><td><strong>${p.name}</strong><br><span class="small muted">${p.dosageForm}</span></td><td class="small">${p.seller}</td><td>${fmtDate(p.fdaExpiry)}</td><td>${status(p.status)}</td><td>${p.purchasable ? status('active', 'Yes') : status('void', 'No')}</td><td><button class="btn small ghost" data-act="viewProd" data-id="${p.id}">Review</button></td></tr>`)}</tbody></table></div>`;
  return html`${head}<div class="table-wrap"><table class="tbl"><thead><tr><th>Practitioner</th><th>Class</th><th>Registration</th><th>Licence to</th><th>Status</th><th></th></tr></thead><tbody>${r.practitioners.map((p) => html`<tr><td><strong>${p.fullName}</strong><br><span class="small muted">${p.title}</span></td><td>${classBadge(p.providerClass, p.classLabel)}</td><td class="mono small">${regLabel(p.council, p.registrationNumber)}</td><td>${fmtDate(p.licenceExpiry)}${p.bookable ? '' : html`<br><span class="small bad-text">Not bookable</span>`}</td><td>${status(p.status)}${p.pendingRenewal ? html`<br><span class="small warn-text">Renewal pending</span>` : ''}</td><td><button class="btn small ghost" data-act="viewPrac" data-id="${p.id}">Review</button></td></tr>`)}</tbody></table></div>`;
}, { auth: true, wide: true });

// ---------- care ----------
route('/a/care', async (ctx) => {
  ctx.title = 'Care & safety';
  ctx.wide = true;
  const tab = ctx.query.tab || 'queue';
  const r = await api('admin.care');
  ctx.act('tab', (d) => go('#/a/care?tab=' + d.v));
  ctx.act('cq', (d) => sheet('Update follow-up', html`<form class="stack" data-form="cq"><input type="hidden" name="id" value="${d.id}">${field('Status', select('status', [['followed_up', 'Followed up'], ['closed', 'Closed'], ['open', 'Keep open']]))}${field('Follow-up note', textarea('note', { rows: 3, placeholder: 'Who you contacted, outcome, referral confirmed…' }))}<p class="form-error" role="alert" hidden></p><button class="btn primary">Save</button></form>`));
  ctx.form('cq', async (v) => { await api('admin.updateCareItem', v); closeSheets(); toast('Saved.'); refresh(); });
  ctx.act('ae', (d) => { const a = r.adverse.find((x) => x.id === d.id); sheet(`Report ${a.code}`, html`<form class="stack" data-form="ae"><input type="hidden" name="id" value="${a.id}">${kv([['Reporter', `${a.reporterName} (${a.reporterRole})`], ['Product', a.productName || '—'], ['Type', cap(a.kind)], ['Severity', a.severity], ['Onset', a.onsetDate || '—'], ['Other medicines', a.otherMedicines || '—'], ['Description', a.description]])}${a.actions.length ? html`<ol class="timeline">${a.actions.map((x) => html`<li class="done"><span class="tl-dot"></span><span>${x.text} <span class="small muted">${x.by}, ${fmtDateTime(x.at)}</span></span></li>`)}</ol>` : ''}${field('Status', select('status', [['under_review', 'Under review'], ['referred_fda', 'Reported to FDA Ghana'], ['closed', 'Closed']], a.status))}${when(a.productId && a.productStatus === 'approved', () => check('quarantine', 'Quarantine product (suspend sales) while investigating'))}${field('Action note', textarea('note', { rows: 3 }))}<p class="form-error" role="alert" hidden></p><button class="btn primary">Save</button></form>`, { wide: true }); });
  ctx.form('ae', async (v) => { await api('admin.updateAdverse', { ...v, quarantine: v.quarantine === true }); closeSheets(); toast('Saved.'); refresh(); });
  ctx.act('tk', (d) => { const t = r.tickets.find((x) => x.id === d.id); sheet(`${t.code}: ${t.subject}`, html`<div class="stack"><p>${status(t.status)} <span class="badge line">${cap(t.kind)}</span> <span class="badge line">${cap(t.category)}</span> ${t.severity === 'high' ? status('urgent', 'High severity') : ''}</p>${when(t.holdApplied, () => html`<p class="note warn">${icon('clock')} Related provider settlement is on hold until this is resolved.</p>`)}<div class="thread">${t.thread.map((m) => html`<div class="msg ${m.role}"><span class="small muted">${m.by} · ${fmtDateTime(m.at)}</span><p>${m.text}</p></div>`)}</div><form class="stack" data-form="tk"><input type="hidden" name="id" value="${t.id}">${field('Reply to customer', textarea('reply', { rows: 3 }))}${field('Status', select('status', [['investigating', 'Investigating'], ['resolved', 'Resolved'], ['closed', 'Closed'], ['open', 'Open']], t.status))}<p class="form-error" role="alert" hidden></p><button class="btn primary">Update</button></form></div>`, { wide: true }); });
  ctx.form('tk', async (v) => { await api('admin.updateTicket', v); closeSheets(); toast('Updated.'); refresh(); });
  ctx.act('rev', async (d) => { const r2 = await confirmSheet({ title: d.v === 'published' ? 'Publish review?' : 'Reject review?', confirmLabel: cap(d.v), danger: d.v === 'rejected', reason: d.v === 'rejected' }); if (!r2.ok) return; await api('admin.moderateReview', { id: d.id, status: d.v, reason: r2.reason }); toast('Saved.'); refresh(); });
  ctx.act('prv', (d) => { const p = r.privacy.find((x) => x.id === d.id); sheet(`${cap(p.type)} request`, html`<form class="stack" data-form="prv"><input type="hidden" name="id" value="${p.id}">${kv([['Customer', p.userName], ['Received', fmtDateTime(p.createdAt)], ['Due by', fmtDate(p.dueBy)], ['Details', p.details || '—']])}${field('Decision', select('decision', [['completed', p.type === 'deletion' ? 'Delete / anonymise account' : 'Completed'], ['declined', 'Decline']]))}${field('Note to customer', textarea('note', { rows: 2 }))}<p class="form-error" role="alert" hidden></p><button class="btn primary">Save</button></form>`); });
  ctx.form('prv', async (v) => { await api('admin.processPrivacy', v); closeSheets(); toast('Processed.'); refresh(); });
  const openQ = r.queue.filter((q) => q.status === 'open').length;
  const head = tabs([['queue', 'Follow-up queue', openQ], ['adverse', 'Adverse events', r.adverse.filter((a) => ['new', 'under_review'].includes(a.status)).length], ['tickets', 'Complaints & support', r.tickets.filter((t) => !['resolved', 'closed'].includes(t.status)).length], ['reviews', 'Reviews', r.reviews.filter((x) => x.status === 'pending').length], ['privacy', 'Privacy', r.privacy.filter((x) => x.status === 'open').length], ['quality', 'Quality']], tab);
  if (tab === 'adverse') return html`${head}${r.adverse.length ? html`<div class="table-wrap"><table class="tbl"><thead><tr><th>Ref</th><th>Product / case</th><th>Type</th><th>Severity</th><th>Status</th><th></th></tr></thead><tbody>${r.adverse.map((a) => html`<tr><td class="mono">${a.code}</td><td>${a.productName || (a.bookingId ? 'Consultation' : '—')}<br><span class="small muted">${a.reporterName}, ${fmtDate(a.createdAt)}</span></td><td>${cap(a.kind)}</td><td>${a.severity === 'severe' ? status('urgent', 'Severe') : cap(a.severity)}</td><td>${status(a.status)}</td><td><button class="btn small ghost" data-act="ae" data-id="${a.id}">Open</button></td></tr>`)}</tbody></table></div>` : empty('No reports')}`;
  if (tab === 'tickets') return html`${head}${r.tickets.length ? html`<div class="table-wrap"><table class="tbl"><thead><tr><th>Ref</th><th>Subject</th><th>Type</th><th>Status</th><th></th></tr></thead><tbody>${r.tickets.map((t) => html`<tr><td class="mono">${t.code}</td><td>${t.subject}<br><span class="small muted">${t.userName} · ${fmtDate(t.createdAt)}</span></td><td>${cap(t.kind)}${t.severity === 'high' ? html`<br>${status('urgent', 'High')}` : ''}</td><td>${status(t.status)}</td><td><button class="btn small ghost" data-act="tk" data-id="${t.id}">Open</button></td></tr>`)}</tbody></table></div>` : empty('No tickets')}`;
  if (tab === 'reviews') return html`${head}<p class="muted small">Reviews describe service experience. Reviews claiming a cure or treatment efficacy are flagged and cannot be published.</p>${r.reviews.length ? html`<div class="stack">${r.reviews.map((x) => html`<div class="card"><div class="row between"><strong>${'★'.repeat(x.rating)} · ${x.targetName}</strong>${status(x.status)}</div><p>${x.text}</p><p class="small muted">${x.authorName} · ${fmtDate(x.createdAt)} ${x.flags.includes('efficacy_claim') ? html`${status('urgent', 'Efficacy claim')}` : ''}</p>${when(x.status === 'pending', () => html`<div class="row"><button class="btn small primary" data-act="rev" data-id="${x.id}" data-v="published" ${x.flags.includes('efficacy_claim') ? raw('disabled title="Contains a cure claim"') : ''}>Publish</button><button class="btn small ghost" data-act="rev" data-id="${x.id}" data-v="rejected">Reject</button></div>`)}</div>`)}</div>` : empty('No reviews')}`;
  if (tab === 'privacy') return html`${head}${r.privacy.length ? html`<div class="list">${r.privacy.map((p) => html`<button type="button" class="list-item" data-act="prv" data-id="${p.id}" ${p.status !== 'open' ? raw('disabled') : ''}><span class="li-main"><strong>${cap(p.type)} · ${p.userName}</strong><span class="small muted">Received ${fmtDate(p.createdAt)} · due ${fmtDate(p.dueBy)}</span></span>${status(p.status)}</button>`)}</div>` : empty('No requests')}`;
  if (tab === 'quality') return html`${head}<div class="table-wrap"><table class="tbl"><thead><tr><th>Practitioner</th><th class="num">Completed</th><th class="num">Provider cancels</th><th class="num">Complaints</th><th class="num">Adverse</th><th class="num">Referrals</th><th class="num">Rating</th></tr></thead><tbody>${r.quality.map((q) => html`<tr><td>${q.fullName}<br><span class="small muted">${q.classLabel} · ${q.status}</span></td><td class="num">${q.completed}</td><td class="num ${q.providerCancellations > 1 ? 'warn-text' : ''}">${q.providerCancellations}</td><td class="num ${q.complaints ? 'warn-text' : ''}">${q.complaints}</td><td class="num">${q.adverse}</td><td class="num">${q.referrals}</td><td class="num">${q.rating.avg ?? '—'}</td></tr>`)}</tbody></table></div>`;
  return html`${head}${r.queue.length ? html`<div class="stack">${r.queue.map((q) => html`<div class="card ${q.status === 'open' && q.priority === 'urgent' ? 'alert-card' : ''}"><div class="row between"><strong>${cap(q.type)}${q.bookingCode ? ` · ${q.bookingCode}` : ''}</strong>${q.status === 'open' && q.priority === 'urgent' ? status('urgent', 'Urgent') : status(q.status)}</div><p>${q.summary}</p><p class="small muted">${q.customerName || ''}${q.practitionerName ? ` · ${q.practitionerName}` : ''} · ${fmtDateTime(q.createdAt)}</p>${(q.notes || []).map((n) => html`<p class="small">↳ ${n.text} <span class="muted">(${n.by})</span></p>`)}${when(q.status === 'open', () => html`<button class="btn small primary" data-act="cq" data-id="${q.id}">Record follow-up</button>`)}</div>`)}</div>` : empty('Nothing needs follow-up')}`;
}, { auth: true, wide: true });

// ---------- finance ----------
route('/a/finance', async (ctx) => {
  ctx.title = 'Finance';
  ctx.wide = true;
  const tab = ctx.query.tab || 'payments';
  const f = await api('admin.finance');
  ctx.act('tab', (d) => go('#/a/finance?tab=' + d.v));
  ctx.act('refund', (d) => {
    const p = f.payments.find((x) => x.id === d.id);
    const orders = p.allocations.filter((a) => a.orderId).map((a) => a.orderId).filter((v, i, arr) => arr.indexOf(v) === i);
    sheet(`Refund ${p.reference}`, html`<form class="stack" data-form="refund"><input type="hidden" name="paymentId" value="${p.id}">
      ${kv([['Paid', money(p.amount)], ['Already refunded', money(p.refunded)], ['For', p.title || p.description]])}
      ${when(orders.length > 1, () => field('Order', select('orderId', orders.map((o) => [o, o]))))}
      ${field('Amount (GH₵)', input('amountGhs', { type: 'number', value: ((p.amount - p.refunded) / 100).toFixed(2), attrs: 'step="0.01" min="0.01"' }))}
      ${when(p.purpose !== 'booking' && p.purpose !== 'subscription', () => check('includeDelivery', 'Amount includes the delivery fee'))}
      ${field('Rule', select('rule', [['manual', 'Manual adjustment'], ['service_recovery', 'Service recovery'], ['product_unavailable', 'Product unavailable'], ['partial_fulfilment', 'Partial fulfilment'], ['customer_cancel_full', 'Customer cancellation'], ['duplicate_payment', 'Duplicate payment']]))}
      ${field('Reason (audit log)', textarea('reason', { rows: 2 }))}
      <p class="muted small">Provider settlement is adjusted automatically. Clinical-outcome complaints alone should not be refunded without clinical review.</p>
      <p class="form-error" role="alert" hidden></p><button class="btn danger">Issue refund</button></form>`);
  });
  ctx.form('refund', async (v) => { await api('admin.refund', { ...v, includeDelivery: v.includeDelivery === true }); closeSheets(); toast('Refund processed and settlement adjusted.'); refresh(); });
  ctx.act('dispute', async (d) => { const r = await confirmSheet({ title: 'Record a chargeback / dispute?', body: 'Related provider settlements are frozen until it is resolved.', confirmLabel: 'Open dispute', danger: true, reason: true }); if (!r.ok) return; await api('admin.openDispute', { paymentId: d.id, kind: 'chargeback', reason: r.reason }); toast('Dispute opened; settlements frozen.'); refresh(); });
  ctx.act('resolve', async (d) => { const r = await confirmSheet({ title: d.v === 'won' ? 'Dispute won?' : 'Dispute lost?', body: d.v === 'won' ? 'Settlement holds are released.' : 'Funds return to the customer and related provider shares are voided.', confirmLabel: 'Resolve', danger: d.v === 'lost', reason: true }); if (!r.ok) return; await api('admin.resolveDispute', { id: d.id, outcome: d.v, reason: r.reason }); toast('Dispute resolved.'); refresh(); });
  ctx.act('settle', async () => { const r = await confirmSheet({ title: 'Run settlement?', body: 'Creates payouts for all eligible, un-held earnings net of refunds and adjustments.', confirmLabel: 'Run settlement' }); if (!r.ok) return; const res = await api('admin.runSettlement'); toast(res.payouts.length ? `${res.payouts.length} payout(s) created, ${money(res.total).replace(' ', ' ')}.` : 'Nothing eligible to settle.'); refresh(); });
  ctx.act('payout', async (d) => { const r = await confirmSheet({ title: d.v === 'paid' ? 'Confirm transfer completed' : 'Mark payout failed', confirmLabel: 'Save', danger: d.v === 'failed', reason: true, reasonLabel: d.v === 'paid' ? 'Bank / MoMo transfer reference' : 'Failure reason' }); if (!r.ok) return; await api('admin.markPayout', { id: d.id, status: d.v, transferRef: r.reason }); toast('Updated.'); refresh(); });
  ctx.act('reconcile', async () => {
    const r = await api('admin.reconcile');
    sheet('Reconciliation', html`<div class="stack">${r.ok ? html`<p class="note">${icon('check')} Ledger balanced: ${r.transactions} transactions, debits ${money(r.totalDebit)} = credits ${money(r.totalCredit)}. Provider balances match unpaid earnings.</p>` : html`<p class="note bad">${icon('alert')} ${r.issues.length} issue(s) found.</p>`}${when(r.issues.length, () => html`<div class="list">${r.issues.map((i) => html`<div class="list-item"><span class="li-main"><strong>${cap(i.type)}</strong><span class="small mono">${i.ref}</span><span class="small">${i.detail}</span></span></div>`)}</div>`)}<p class="small muted">Checked ${fmtDateTime(r.checkedAt)}</p></div>`, { wide: true });
  });
  ctx.act('pf', () => sheet('Invoice partnership fee', html`<form class="stack" data-form="pf">${field('Partner', select('orgId', f.orgs.map((o) => [o.id, o.name])))}${field('Amount (GH₵)', input('amountGhs', { type: 'number' }))}${field('Period', input('period', { placeholder: 'e.g. Q4 2026' }))}<p class="form-error" role="alert" hidden></p><button class="btn primary">Create invoice</button></form>`));
  ctx.form('pf', async (v) => { await api('admin.partnerFee', v); closeSheets(); toast('Invoice recorded.'); refresh(); });
  ctx.act('pfpaid', async (d) => { await api('admin.partnerFee', { id: d.id }); toast('Marked paid.'); refresh(); });
  ctx.form('settings', async (v) => { await api('admin.updateSettings', v); toast('Settings saved.'); refresh(); });
  const head = html`<div class="row between wrap">${tabs([['payments', 'Payments'], ['refunds', 'Refunds'], ['disputes', 'Disputes', f.disputes.filter((d) => d.status === 'open').length], ['settlements', 'Settlements'], ['ledger', 'Ledger'], ['fees', 'Partner fees'], ['settings', 'Settings']], tab)}<button class="btn small ghost" data-act="reconcile">${icon('refresh')} Reconcile</button></div>`;
  if (tab === 'refunds') return html`${head}<div class="table-wrap"><table class="tbl"><thead><tr><th>Ref</th><th>When</th><th>Rule</th><th>Reason</th><th class="num">Amount</th><th class="num">Provider share adj.</th><th>By</th></tr></thead><tbody>${f.refunds.map((r) => html`<tr><td class="mono">${r.code}</td><td>${fmtDateTime(r.at)}</td><td>${cap(r.rule)}</td><td class="small">${r.reason}</td><td class="num">${money(r.amount)}</td><td class="num">${r.providerPortion ? '−' + money(r.providerPortion) : '—'}</td><td>${r.by}</td></tr>`)}</tbody></table></div>`;
  if (tab === 'disputes') return html`${head}${f.disputes.length ? html`<div class="table-wrap"><table class="tbl"><thead><tr><th>Ref</th><th>Payment</th><th>Reason</th><th class="num">Amount</th><th>Status</th><th></th></tr></thead><tbody>${f.disputes.map((d) => html`<tr><td class="mono">${d.code}</td><td class="mono">${d.reference}</td><td>${d.reason}</td><td class="num">${money(d.amount)}</td><td>${status(d.status)}</td><td>${when(d.status === 'open', () => html`<button class="btn small ghost" data-act="resolve" data-id="${d.id}" data-v="won">Won</button> <button class="btn small ghost" data-act="resolve" data-id="${d.id}" data-v="lost">Lost</button>`)}</td></tr>`)}</tbody></table></div>` : empty('No disputes', 'Record a chargeback from the Payments tab.')}`;
  if (tab === 'settlements') {
    const byStatus = (s) => f.earnings.filter((e) => e.status === s);
    return html`${head}<div class="stats"><div><strong>${money(byStatus('eligible').reduce((s, e) => s + e.net, 0))}</strong><span>eligible now</span></div><div><strong>${money(byStatus('pending').reduce((s, e) => s + e.net, 0))}</strong><span>in hold period</span></div><div><strong>${money(byStatus('on_hold').reduce((s, e) => s + e.net, 0))}</strong><span>held (complaint, dispute, recall)</span></div></div>
      <button class="btn primary" data-act="settle">Run settlement</button>
      ${section('Payouts', f.payouts.length ? html`<div class="table-wrap"><table class="tbl"><thead><tr><th>Ref</th><th>Beneficiary</th><th>Destination</th><th class="num">Amount</th><th>Status</th><th></th></tr></thead><tbody>${f.payouts.map((p) => html`<tr><td class="mono">${p.reference}</td><td>${p.beneficiaryName}<br><span class="small muted">${p.lines.length} item(s) · ${fmtDate(p.createdAt)}</span></td><td class="small">${p.destination}</td><td class="num">${money(p.amount)}</td><td>${status(p.status)}${p.transferRef ? html`<br><span class="small mono">${p.transferRef}</span>` : ''}</td><td>${when(p.status === 'processing', () => html`<button class="btn small ghost" data-act="payout" data-id="${p.id}" data-v="paid">Transferred</button> <button class="btn small ghost" data-act="payout" data-id="${p.id}" data-v="failed">Failed</button>`)}</td></tr>`)}</tbody></table></div>` : html`<p class="muted">No payouts yet.</p>`)}
      ${section('Earnings', html`<div class="table-wrap"><table class="tbl"><thead><tr><th>Item</th><th>Beneficiary</th><th class="num">Gross</th><th class="num">Commission</th><th class="num">Adj.</th><th class="num">Net</th><th>Status</th></tr></thead><tbody>${f.earnings.map((e) => html`<tr><td>${e.label}${e.holds.length ? html`<br><span class="small warn-text">${e.holds.join(', ')}</span>` : ''}${e.eligibleAt && e.status === 'pending' ? html`<br><span class="small muted">eligible ${fmtDate(e.eligibleAt)}</span>` : ''}</td><td>${e.beneficiary}</td><td class="num">${money(e.gross)}</td><td class="num">${money(e.commission)}</td><td class="num">${money(e.adjustments)}</td><td class="num"><b>${money(e.net)}</b></td><td>${status(e.status)}</td></tr>`)}</tbody></table></div>`)}`;
  }
  if (tab === 'ledger') return html`${head}${section('Account balances', html`<div class="table-wrap"><table class="tbl"><thead><tr><th>Account</th><th class="num">Debit</th><th class="num">Credit</th><th class="num">Balance</th></tr></thead><tbody>${f.accounts.map((a) => html`<tr><td>${a.label}<br><span class="small mono muted">${a.account}</span></td><td class="num">${money(a.debit)}</td><td class="num">${money(a.credit)}</td><td class="num">${money(Math.abs(a.balance))} ${a.balance >= 0 ? 'Dr' : 'Cr'}</td></tr>`)}</tbody></table></div>`)}
    ${section('Journal (latest 300 lines)', html`<div class="table-wrap"><table class="tbl small"><thead><tr><th>When</th><th>Txn</th><th>Account</th><th class="num">Debit</th><th class="num">Credit</th><th>Memo</th></tr></thead><tbody>${f.ledger.map((l) => html`<tr><td>${fmtDateTime(l.at)}</td><td class="mono">${l.txnId.slice(-6)}</td><td class="mono">${l.account}</td><td class="num">${l.debit ? money(l.debit) : ''}</td><td class="num">${l.credit ? money(l.credit) : ''}</td><td>${l.memo}</td></tr>`)}</tbody></table></div>`)}`;
  if (tab === 'fees') return html`${head}<button class="btn primary" data-act="pf">${icon('plus')} Invoice partnership fee</button>${f.partnerFees.length ? html`<div class="table-wrap"><table class="tbl"><thead><tr><th>Ref</th><th>Partner</th><th>Period</th><th class="num">Amount</th><th>Status</th><th></th></tr></thead><tbody>${f.partnerFees.map((p) => html`<tr><td class="mono">${p.code}</td><td>${p.orgName}</td><td>${p.period}</td><td class="num">${money(p.amount)}</td><td>${status(p.status === 'invoiced' ? 'pending' : 'paid', cap(p.status))}</td><td>${when(p.status === 'invoiced', () => html`<button class="btn small ghost" data-act="pfpaid" data-id="${p.id}">Mark paid</button>`)}</td></tr>`)}</tbody></table></div>` : empty('No partnership fees yet')}`;
  if (tab === 'settings') {
    const s = f.settings;
    if (!has('admin')) return html`${head}${kv([['Consultation commission', s.consultationCommissionPct + '%'], ['Product commission', s.productCommissionPct + '%'], ['Consultation hold', s.holdDaysConsultation + ' days'], ['Product hold', s.holdDaysProduct + ' days'], ['Delivery fee', money(s.deliveryFee)]])}`;
    return html`${head}<form class="card stack" data-form="settings" novalidate><div class="grid2">${field('Consultation commission %', input('consultationCommissionPct', { type: 'number', value: s.consultationCommissionPct }))}${field('Product commission %', input('productCommissionPct', { type: 'number', value: s.productCommissionPct }))}</div><div class="grid2">${field('Consultation settlement hold (days)', input('holdDaysConsultation', { type: 'number', value: s.holdDaysConsultation }))}${field('Product settlement hold (days)', input('holdDaysProduct', { type: 'number', value: s.holdDaysProduct }))}</div><div class="grid2">${field('Delivery fee (GH₵)', input('deliveryFeeGhs', { type: 'number', value: s.deliveryFee / 100, attrs: 'step="0.5"' }))}${field('Plus monthly fee (GH₵)', input('plusMonthlyFeeGhs', { type: 'number', value: s.plusMonthlyFee / 100 }))}</div>${field('Reason for change (audit log)', input('reason'))}<p class="form-error" role="alert" hidden></p><button class="btn primary">Save settings</button></form>`;
  }
  return html`${head}<div class="table-wrap"><table class="tbl"><thead><tr><th>Reference</th><th>When</th><th>Customer</th><th>For</th><th>Method</th><th class="num">Amount</th><th>Allocation</th><th>Status</th><th></th></tr></thead><tbody>${f.payments.map((p) => html`<tr><td class="mono">${p.reference}<br><span class="small muted">${p.receiptNo}</span></td><td>${fmtDateTime(p.paidAt || p.createdAt)}</td><td>${p.customerName}</td><td class="small">${p.title || p.description}<br><span class="muted">${p.provider}</span></td><td>${p.channel === 'mobile_money' ? 'MoMo' : 'Card'}</td><td class="num">${money(p.amount)}${p.refunded ? html`<br><span class="small warn-text">−${money(p.refunded)}</span>` : ''}</td><td class="small">${p.allocations.map((a) => html`${words(a.kind)}: ${money(a.amount)}<br>`)}</td><td>${status(p.status)}</td><td>${when(p.status === 'success' && p.refunded < p.amount, () => html`<button class="btn small ghost" data-act="refund" data-id="${p.id}">Refund</button> <button class="btn small ghost" data-act="dispute" data-id="${p.id}">Chargeback</button>`)}</td></tr>`)}</tbody></table></div>`;
}, { auth: true, wide: true });

// ---------- risk ----------
route('/a/risk', async (ctx) => {
  ctx.title = 'Risk & audit';
  ctx.wide = true;
  const tab = ctx.query.tab || 'audit';
  const r = await api('admin.risk', { q: ctx.query.q || '' });
  ctx.act('tab', (d) => go('#/a/risk?tab=' + d.v));
  ctx.form('q', (v) => go(`#/a/risk?tab=audit&q=${encodeURIComponent(v.q || '')}`));
  ctx.form('flags', async (v) => { await api('admin.setFlags', { conventionalPharmacy: v.conventionalPharmacy === true, subscriptions: v.subscriptions === true, videoConsultations: v.videoConsultations === true, twi: v.twi === true, reason: v.reason }); S.meta = await api('meta.get'); toast('Feature flags saved.'); refresh(); });
  ctx.act('unlock', async (d) => { const x = await confirmSheet({ title: 'Unlock account?', confirmLabel: 'Unlock', reason: true }); if (!x.ok) return; await api('admin.unlockUser', { id: d.id, reason: x.reason }); toast('Unlocked.'); refresh(); });
  const head = tabs([['audit', 'Audit log'], ['expiring', 'Expiring evidence', r.expiring.filter((e) => e.daysLeft <= 30).length], ['security', 'Security'], ['flags', 'Feature flags'], ['roles', 'Roles']], tab);
  if (tab === 'expiring') return html`${head}<p class="muted small">Expired evidence blocks bookings and sales automatically. Reminders go out 30 days before.</p>${r.expiring.length ? html`<div class="table-wrap"><table class="tbl"><thead><tr><th>Type</th><th>Name</th><th>Expiry</th><th class="num">Days left</th></tr></thead><tbody>${r.expiring.map((e) => html`<tr><td>${e.kind}</td><td>${e.name}</td><td>${fmtDate(e.expiry)}</td><td class="num ${e.daysLeft < 0 ? 'bad-text' : e.daysLeft <= 30 ? 'warn-text' : ''}">${e.daysLeft}</td></tr>`)}</tbody></table></div>` : empty('Nothing expiring in the next 60 days')}`;
  if (tab === 'security') return html`${head}${section('Locked accounts', r.lockedAccounts.length ? html`<div class="list">${r.lockedAccounts.map((u) => html`<div class="list-item"><span class="li-main"><strong>${u.email}</strong><span class="small muted">until ${fmtDateTime(u.until)}</span></span><button class="btn small ghost" data-act="unlock" data-id="${u.id}">Unlock</button></div>`)}</div>` : html`<p class="muted">None.</p>`)}${section('Failed sign-ins', r.failedLogins.length ? html`<div class="table-wrap"><table class="tbl"><thead><tr><th>When</th><th>Account</th><th>Device</th></tr></thead><tbody>${r.failedLogins.map((l) => html`<tr><td>${fmtDateTime(l.at)}</td><td>${l.email}</td><td>${l.device}</td></tr>`)}</tbody></table></div>` : html`<p class="muted">None.</p>`)}<p class="note">${icon('lock')} Privileged roles (admin, finance, support, supervisor) sign in with a one-time SMS code. Sessions end after ${r.settings.sessionIdleMinutes} minutes idle; accounts lock for 15 minutes after 5 failed attempts.</p>`;
  if (tab === 'flags') return html`${head}<form class="card stack" data-form="flags" novalidate>
    ${check('conventionalPharmacy', html`<strong>Prescription medicines via partner pharmacies</strong><br><span class="small muted">Phase 3. Enable only after formal legal and regulatory confirmation.</span>`, r.flags.conventionalPharmacy)}
    ${check('subscriptions', html`<strong>PRORESMAT Plus subscription</strong><br><span class="small muted">Premium features; enable once the value proposition is agreed.</span>`, r.flags.subscriptions)}
    ${check('videoConsultations', html`<strong>Video consultations</strong>`, r.flags.videoConsultations)}
    ${check('twi', html`<strong>Twi language option</strong><br><span class="small muted">Draft translations pending language review.</span>`, r.flags.twi)}
    ${field('Reason (audit log)', input('reason'))}<p class="form-error" role="alert" hidden></p><button class="btn primary">Save flags</button></form>`;
  if (tab === 'roles') return html`${head}<div class="table-wrap"><table class="tbl"><thead><tr><th>Name</th><th>Email</th><th>Roles</th></tr></thead><tbody>${r.roles.map((u) => html`<tr><td>${u.name}</td><td>${u.email}</td><td>${u.roles.map((x) => html`<span class="badge line">${x}</span> `)}</td></tr>`)}</tbody></table></div>
    ${section('Permission matrix', html`<div class="table-wrap"><table class="tbl small"><thead><tr><th>Capability</th><th>Customer</th><th>Practitioner</th><th>Supervisor</th><th>Vendor</th><th>Finance</th><th>Support</th><th>Admin</th></tr></thead><tbody>${[
      ['Book & pay, own records', 1, 1, 1, 1, 0, 0, 0], ['Clinical notes (own patients)', 0, 1, 1, 0, 0, 0, 0], ['Supervisee case review', 0, 0, 1, 0, 0, 0, 0], ['Medical documents (shared with them)', 1, 1, 1, 0, 0, 0, 0], ['Listings & fulfilment (own org)', 0, 0, 0, 1, 0, 0, 0],
      ['Payments, refunds, settlements', 0, 0, 0, 0, 1, 0, 1], ['Complaints, care queue, reviews', 0, 0, 0, 0, 0, 1, 1], ['Approvals, recalls, flags, audit', 0, 0, 0, 0, 0, 0, 1],
    ].map(([cap_, ...cells]) => html`<tr><td>${cap_}</td>${cells.map((c) => html`<td>${c ? '✓' : '—'}</td>`)}</tr>`)}</tbody></table></div><p class="muted small">Finance, support and admin staff cannot open clinical notes or medical documents.</p>`)}`;
  return html`${head}<form class="search" data-form="q" role="search">${icon('search')}<input name="q" type="search" value="${ctx.query.q || ''}" placeholder="Filter by action, person, record or reason" aria-label="Filter audit log"><button class="btn small primary">Filter</button></form>${auditList(r.audit)}`;
}, { auth: true, wide: true });

export { raw };
