// Demo data. Past activity is generated by running the real workflows with the clock moved back,
// so every payment, ledger posting, earning and audit entry is produced by the same rules as live use.
import { hashPassword, newId } from './util.js';

export const DEMO_PASSWORD = 'Demo@1234';
export const DEMO_ACCOUNTS = [
  { email: 'akosua@demo.gh', label: 'Customer', env: 'customer', note: 'Has history: consultations, care plan, orders' },
  { email: 'kojo@demo.gh', label: 'Customer (2)', env: 'customer', note: 'Upcoming consultation, open order' },
  { email: 'kwame@demo.gh', label: 'Practitioner + supervisor', env: 'practitioner', note: 'PRORESMAT-supervised; consultation starting soon; one-time code' },
  { email: 'ama@demo.gh', label: 'Practitioner', env: 'practitioner', note: 'Supervised medical herbalist' },
  { email: 'kofi@demo.gh', label: 'Practitioner (conventional)', env: 'practitioner', note: 'Independent; can issue prescriptions' },
  { email: 'clinic@demo.gh', label: 'Clinic vendor', env: 'vendor', note: 'Nkabom Herbal Clinic: orders to fulfil' },
  { email: 'store@demo.gh', label: 'PRORESMAT store', env: 'vendor', note: 'Fulfils products sold by PRORESMAT' },
  { email: 'pharmacy@demo.gh', label: 'Pharmacy partner', env: 'vendor', note: 'Validates prescriptions (when enabled)' },
  { email: 'adwoa@demo.gh', label: 'Clinic (pending)', env: 'vendor', note: 'Awaiting PRORESMAT approval' },
  { email: 'admin@demo.gh', label: 'PRORESMAT admin', env: 'admin', note: 'All control-centre areas; one-time code' },
  { email: 'finance@demo.gh', label: 'Finance', env: 'admin', note: 'Ledger, refunds, settlements; one-time code' },
  { email: 'support@demo.gh', label: 'Support', env: 'admin', note: 'Complaints, care queue, reviews; one-time code' },
];

const H = 3600000;
const D = 86400000;

export async function seedDatabase(E) {
  const db = E.db;
  const today = E.today();
  const plusDays = (n) => E.addDays(today, n);
  const { salt, hash } = await hashPassword(DEMO_PASSWORD);

  const user = (id, name, email, phone, roles, extra = {}) => E.insert('users', {
    id, name, email, phone, roles, lang: 'en', status: 'active', salt, hash, createdAt: new Date(E.now() - 60 * D).toISOString(),
    consentAt: new Date(E.now() - 60 * D).toISOString(), consentVersion: '2026-08', health: { allergies: '', currentMeds: '', conditions: '' }, failed: 0, lockedUntil: null, ...extra,
  });

  const akosua = user('usr_akosua', 'Akosua Mensah', 'akosua@demo.gh', '+233244123456', ['customer'], { address: 'House 14, Abelemkpe Road, Accra', dob: '1990-03-14', health: { allergies: 'Penicillin', currentMeds: 'None', conditions: 'Mild hypertension (monitored)' } });
  const kojo = user('usr_kojo', 'Kojo Antwi', 'kojo@demo.gh', '+233201987654', ['customer'], { address: 'Plot 7, Adum, Kumasi', dob: '1984-11-02' });
  const uKwame = user('usr_kwame', 'Nana Kwame Asante', 'kwame@demo.gh', '+233277111222', ['customer', 'practitioner', 'supervisor']);
  const uAma = user('usr_ama', 'Ama Boateng', 'ama@demo.gh', '+233244555666', ['customer', 'practitioner']);
  const uKofi = user('usr_kofi', 'Dr Kofi Mensah', 'kofi@demo.gh', '+233208333444', ['customer', 'practitioner']);
  const uEfua = user('usr_efua', 'Efua Owusu', 'efua@demo.gh', '+233246777888', ['customer', 'practitioner']);
  const uYaw = user('usr_yaw', 'Yaw Darko', 'yaw@demo.gh', '+233249000111', ['customer', 'practitioner']);
  const uAbena = user('usr_abena', 'Abena Ofori', 'abena@demo.gh', '+233245222333', ['customer', 'practitioner']);
  const uClinic = user('usr_clinic', 'Esi Nkansah', 'clinic@demo.gh', '+233302700800', ['customer', 'vendor']);
  const uStore = user('usr_store', 'PRORESMAT Dispensary', 'store@demo.gh', '+233302111000', ['vendor']);
  const uPharm = user('usr_pharm', 'Kwesi Appiah', 'pharmacy@demo.gh', '+233302900100', ['customer', 'vendor']);
  const uAdwoa = user('usr_adwoa', 'Adwoa Sarpong', 'adwoa@demo.gh', '+233243444555', ['customer', 'vendor']);
  const admin = user('usr_admin', 'Mercy Adjei', 'admin@demo.gh', '+233244000001', ['admin']);
  user('usr_finance', 'Samuel Tetteh', 'finance@demo.gh', '+233244000002', ['finance']);
  user('usr_support', 'Linda Quaye', 'support@demo.gh', '+233244000003', ['support']);

  // ---------- organisations ----------
  const org = (id, rec) => E.insert('orgs', { id, statusHistory: [{ status: rec.status, at: new Date(E.now() - 50 * D).toISOString(), by: 'Mercy Adjei', reason: 'Verified at onboarding' }], createdAt: new Date(E.now() - 55 * D).toISOString(), agreementAcceptedAt: new Date(E.now() - 55 * D).toISOString(), ...rec });
  const settle = (bank, name, acct) => ({ method: 'bank', bankName: bank, accountName: name, accountNumber: acct });
  org('org_proresmat', { type: 'proresmat', name: 'PRORESMAT', ownerId: uStore.id, status: 'active', address: 'PRORESMAT Dispensary, 5 Liberation Road, Airport Residential, Accra', phone: '+233302111000', facilityLicenceNo: 'TMPC/FAC/0001', licenceExpiry: plusDays(400), refundTerms: 'Unopened products can be returned within 7 days of delivery. Damaged or wrong items are refunded in full, including delivery.', taxId: 'C0000000001', businessRegNo: 'CS000000001' });
  org('org_nkabom', { type: 'clinic', name: 'Nkabom Herbal Clinic', ownerId: uClinic.id, status: 'active', address: '22 Asafo Market Road, Kumasi', phone: '+233302700800', facilityLicenceNo: 'TMPC/FAC/2231', licenceExpiry: plusDays(210), description: 'Community herbal clinic established in 2009, offering consultations and locally produced FDA-registered herbal preparations.', refundTerms: 'Unopened items may be returned within 5 days. Faulty items are replaced or refunded.', taxId: 'C0034567890', businessRegNo: 'CS123456789', beneficialOwner: { name: 'Esi Nkansah', idNumber: 'GHA-712345678-1', ownershipPct: 100 }, authorisedRep: { name: 'Esi Nkansah', position: 'Director', phone: '+233302700800' }, settlement: settle('GCB Bank', 'Nkabom Herbal Clinic', '1021304050607') });
  org('org_carerx', { type: 'pharmacy', name: 'CareRx Pharmacy', ownerId: uPharm.id, status: 'active', address: '3 Oxford Street, Osu, Accra', phone: '+233302900100', facilityLicenceNo: 'PC/RP/10442', licenceExpiry: plusDays(300), superintendentPharmacist: 'Kwesi Appiah', pharmacyCouncilLicence: 'PC/PH/5521', refundTerms: 'Dispensed prescription medicines cannot be returned unless faulty or dispensed in error.', taxId: 'C0098765432', businessRegNo: 'CS987654321', settlement: settle('Ecobank Ghana', 'CareRx Pharmacy Ltd', '0040123456789') });
  org('org_adwoa', { type: 'clinic', name: 'Adwoa Herbal Centre', ownerId: uAdwoa.id, status: 'submitted', address: '8 Commercial Street, Cape Coast', phone: '+233243444555', facilityLicenceNo: 'TMPC/FAC/3310', licenceExpiry: plusDays(330), refundTerms: 'Returns accepted within 7 days for unopened items.', taxId: 'P0011223344', businessRegNo: 'BN556677889', beneficialOwner: { name: 'Adwoa Sarpong', idNumber: 'GHA-798765432-5', ownershipPct: 100 }, authorisedRep: { name: 'Adwoa Sarpong', position: 'Owner', phone: '+233243444555' }, settlement: { method: 'momo', momoProvider: 'mtn', momoNumber: '+233243444555', accountName: 'Adwoa Sarpong' } });
  uStore.orgId = 'org_proresmat'; uClinic.orgId = 'org_nkabom'; uPharm.orgId = 'org_carerx'; uAdwoa.orgId = 'org_adwoa';

  // ---------- practitioners ----------
  const agreements = { provider: new Date(E.now() - 50 * D).toISOString(), confidentiality: new Date(E.now() - 50 * D).toISOString(), conduct: new Date(E.now() - 50 * D).toISOString() };
  const prac = (id, u, rec) => {
    const p = E.insert('practitioners', { id, userId: u.id, identity: { idType: 'ghana_card', idNumber: rec.idNumber, verified: rec.status === 'active' }, agreements, statusHistory: [{ status: rec.status, at: new Date(E.now() - 45 * D).toISOString(), by: 'Mercy Adjei', reason: rec.status === 'active' ? 'Credentials verified' : 'Application submitted' }], evidenceDocIds: [], createdAt: new Date(E.now() - 50 * D).toISOString(), canPrescribe: false, isSupervisor: false, supervisorId: null, orgId: null, ...rec });
    u.practitionerId = p.id;
    return p;
  };
  const wk = (wins, days = ['mon', 'tue', 'wed', 'thu', 'fri']) => Object.fromEntries(days.map((d) => [d, wins]));
  const kwame = prac('prc_kwame', uKwame, {
    fullName: 'Nana Kwame Asante', title: 'Traditional Medicine Practitioner', category: 'traditional', practiceArea: 'General traditional medicine, digestive and joint complaints',
    qualification: 'Certificate in Traditional Medicine Practice (TMPC); 22 years in practice', council: 'TMPC', registrationNumber: 'TMPC/TMP/0482', licenceExpiry: plusDays(240),
    facility: { name: 'PRORESMAT Integrative Clinic, Kumasi', licenceNo: 'TMPC/FAC/0002', licenceExpiry: plusDays(400), address: '14 Hospital Road, Kumasi' },
    languages: ['English', 'Twi'], location: 'Kumasi', modes: ['physical', 'telephone', 'video'], fee: 12000, providerClass: 'supervised', isSupervisor: true, status: 'active', idNumber: 'GHA-701234567-2',
    bio: 'Nana Kwame leads PRORESMAT’s traditional medicine team in Kumasi and supervises practitioners across the network. He works closely with conventional facilities and refers patients whenever hospital care is needed.',
    avatar: { initials: 'KA', hue: 152 }, settlement: { method: 'momo', momoProvider: 'mtn', momoNumber: '+233277111222', accountName: 'Kwame Asante' },
    availability: { slotMinutes: 30, weekly: { ...wk([['08:00', '12:00'], ['14:00', '17:00']], ['mon', 'tue', 'wed', 'thu', 'fri', 'sat']) }, blockedDates: [] },
  });
  prac('prc_ama', uAma, {
    fullName: 'Ama Boateng', title: 'Medical Herbalist', category: 'herbalist', practiceArea: 'Women’s health, nutrition and wellness', qualification: 'BSc Herbal Medicine (KNUST)',
    council: 'TMPC', registrationNumber: 'TMPC/MH/1177', licenceExpiry: plusDays(25), facility: { name: 'PRORESMAT Integrative Clinic, Accra', licenceNo: 'TMPC/FAC/0001', licenceExpiry: plusDays(400), address: '5 Liberation Road, Accra' },
    languages: ['English', 'Twi', 'Ga'], location: 'Accra', modes: ['physical', 'telephone', 'video'], fee: 10000, providerClass: 'supervised', supervisorId: kwame.id, status: 'active', idNumber: 'GHA-723456789-3',
    bio: 'Ama is a KNUST-trained medical herbalist focusing on nutrition, menstrual health and lifestyle support. She practises under PRORESMAT clinical supervision.',
    avatar: { initials: 'AB', hue: 28 }, settlement: settle('Fidelity Bank', 'Ama Boateng', '2400112233445'),
    availability: { slotMinutes: 30, weekly: wk([['09:00', '13:00'], ['14:00', '16:00']]), blockedDates: [] },
  });
  prac('prc_kofi', uKofi, {
    fullName: 'Dr Kofi Mensah', title: 'Medical Officer (General Practice)', category: 'conventional', practiceArea: 'General practice, chronic disease review, integrative care referrals', qualification: 'MBChB (University of Ghana)',
    council: 'MDC', registrationNumber: 'MDC/RN/8812', licenceExpiry: plusDays(300), facility: { name: 'Osu Family Clinic', licenceNo: 'HeFRA/GA/0923', licenceExpiry: plusDays(280), address: '12 Cantonments Road, Osu, Accra' },
    languages: ['English', 'Twi', 'Ewe'], location: 'Accra', modes: ['physical', 'telephone', 'video'], fee: 20000, providerClass: 'independent', canPrescribe: true, status: 'active', idNumber: 'GHA-734567890-4',
    bio: 'Dr Mensah is an independent general practitioner who reviews patients using traditional and herbal products alongside conventional treatment, including herb–drug interaction checks.',
    avatar: { initials: 'KM', hue: 205 }, settlement: settle('Stanbic Bank', 'Kofi Mensah', '9040001122334'),
    availability: { slotMinutes: 20, weekly: wk([['09:00', '12:00'], ['13:00', '16:00']]), blockedDates: [] },
  });
  prac('prc_efua', uEfua, {
    fullName: 'Efua Owusu', title: 'Traditional Medicine Practitioner', category: 'traditional', practiceArea: 'Musculoskeletal complaints and traditional massage therapy', qualification: 'Certificate in Traditional Medicine Practice (TMPC)',
    council: 'TMPC', registrationNumber: 'TMPC/TMP/0911', licenceExpiry: plusDays(150), facility: { name: 'Efua Owusu Healing Home', licenceNo: 'TMPC/FAC/1788', licenceExpiry: plusDays(150), address: '4 Jukwa Road, Cape Coast' },
    languages: ['English', 'Fante'], location: 'Cape Coast', modes: ['physical', 'telephone'], fee: 8000, providerClass: 'independent', status: 'active', idNumber: 'GHA-745678901-5',
    bio: 'Efua runs a small traditional practice in Cape Coast. She is an independent practitioner verified by PRORESMAT.', avatar: { initials: 'EO', hue: 330 },
    settlement: { method: 'momo', momoProvider: 'telecel', momoNumber: '+233246777888', accountName: 'Efua Owusu' },
    availability: { slotMinutes: 30, weekly: wk([['08:00', '12:00']], ['tue', 'thu', 'sat']), blockedDates: [] },
  });
  prac('prc_yaw', uYaw, {
    fullName: 'Yaw Darko', title: 'Traditional Medicine Practitioner', category: 'traditional', practiceArea: 'General traditional medicine', qualification: 'Certificate in Traditional Medicine Practice (TMPC)',
    council: 'TMPC', registrationNumber: 'TMPC/TMP/0350', licenceExpiry: plusDays(-3), facility: { name: 'Darko Herbal Home', licenceNo: 'TMPC/FAC/1402', licenceExpiry: plusDays(100), address: 'Tamale' },
    languages: ['English', 'Dagbani'], location: 'Tamale', modes: ['physical', 'telephone'], fee: 7000, providerClass: 'independent', status: 'active', idNumber: 'GHA-756789012-6',
    bio: 'Licence expired: this profile is automatically hidden from search and cannot be booked.', avatar: { initials: 'YD', hue: 60 },
    settlement: { method: 'momo', momoProvider: 'mtn', momoNumber: '+233249000111', accountName: 'Yaw Darko' }, availability: { slotMinutes: 30, weekly: wk([['09:00', '15:00']]), blockedDates: [] },
  });
  prac('prc_abena', uAbena, {
    fullName: 'Abena Ofori', title: 'Medical Herbalist', category: 'herbalist', practiceArea: 'Skin conditions and wellness', qualification: 'BSc Herbal Medicine (KNUST)',
    council: 'TMPC', registrationNumber: 'TMPC/MH/1402', licenceExpiry: plusDays(360), facility: { name: 'Green Leaf Wellness, Takoradi', licenceNo: 'TMPC/FAC/2004', licenceExpiry: plusDays(200), address: 'Market Circle, Takoradi' },
    languages: ['English', 'Fante'], location: 'Takoradi', modes: ['physical', 'video'], fee: 9000, providerClass: 'independent', status: 'submitted', submittedAt: new Date(E.now() - 2 * D).toISOString(), idNumber: 'GHA-767890123-7',
    bio: 'Medical herbalist with five years’ experience in skin and wellness consultations.', avatar: { initials: 'AO', hue: 265 },
    settlement: settle('Absa Bank Ghana', 'Abena Ofori', '0331122334455'), availability: { slotMinutes: 30, weekly: wk([['09:00', '14:00']]), blockedDates: [] },
  });

  // ---------- products ----------
  const product = (id, orgId, status, rec) => E.insert('products', {
    id, orgId, status, statusHistory: [{ status, at: new Date(E.now() - 30 * D).toISOString(), by: status === 'draft' ? 'Seller' : 'Mercy Adjei', reason: status === 'approved' ? 'Evidence and claims verified' : status === 'submitted' ? 'Submitted for review' : status === 'recalled' ? 'Microbial contamination found in batch NK-JR-0923' : 'Created' }],
    batches: [], createdAt: new Date(E.now() - 40 * D).toISOString(), delivery: true, pickup: true, returnEligible: true, returnPolicy: 'Unopened items within 7 days of delivery.', strength: '', ...rec,
  });
  product('prd_moringa', 'org_proresmat', 'approved', {
    name: 'Moringa Leaf Capsules', dosageForm: 'Capsule', packSize: '60 × 500 mg capsules', category: 'Nutrition & wellness', fdaRegNo: 'FDA/HD.23-0412', fdaExpiry: plusDays(500), manufacturer: 'PRORESMAT Botanicals Ltd, Accra',
    ingredients: 'Moringa oleifera dried leaf powder 500 mg per capsule; capsule shell (hydroxypropyl methylcellulose).', strength: '500 mg', indication: 'Traditionally used as a nutritional supplement to support general wellbeing.',
    directions: 'Adults: 2 capsules twice daily after meals with water.', duration: '30 days', warnings: 'Stop use and seek advice if you develop stomach upset or a rash. Keep out of reach of children.',
    contraindications: 'Not for children under 12. Avoid if you are allergic to moringa.', pregnancy: 'Not recommended during pregnancy or breastfeeding without advice from your practitioner.',
    interactions: 'May lower blood sugar and blood pressure. Speak to a practitioner if you take diabetes, blood pressure or thyroid medicines.', price: 6500, stock: 120, image: { hue: 110, shape: 'Capsule' },
  });
  product('prd_cryptolepis', 'org_proresmat', 'approved', {
    name: 'Cryptolepis Herbal Tea', dosageForm: 'Tea bags', packSize: '20 tea bags', category: 'Traditional herbal medicines', fdaRegNo: 'FDA/HD.22-0977', fdaExpiry: plusDays(420), manufacturer: 'PRORESMAT Botanicals Ltd, Accra',
    ingredients: 'Cryptolepis sanguinolenta root 1.5 g per tea bag.', strength: '1.5 g per bag', indication: 'Traditionally used to support recovery from feverish illness. Get tested for malaria first; see a clinician if fever lasts more than 2 days.',
    directions: 'Infuse 1 bag in a cup of hot water for 5 minutes. Drink 1 cup three times daily.', duration: '7 days', warnings: 'Do not use instead of a malaria test or prescribed treatment. Seek urgent care for high fever in children.',
    contraindications: 'Not for children under 12. Avoid with known liver disease.', pregnancy: 'Do not use during pregnancy or breastfeeding.',
    interactions: 'May interact with antimalarial and blood-thinning medicines. Tell your practitioner about all medicines you take.', price: 4500, stock: 80, image: { hue: 12, shape: 'Tea bags' },
  });
  product('prd_ginger', 'org_proresmat', 'approved', {
    name: 'Ginger & Lemongrass Digestive Tea', dosageForm: 'Tea bags', packSize: '25 tea bags', category: 'Teas & infusions', fdaRegNo: 'FDA/HD.24-0133', fdaExpiry: plusDays(600), manufacturer: 'PRORESMAT Botanicals Ltd, Accra',
    ingredients: 'Zingiber officinale rhizome 1 g, Cymbopogon citratus leaf 0.8 g per bag.', indication: 'Traditionally used to ease occasional indigestion and bloating.',
    directions: 'Infuse 1 bag for 5 minutes. Up to 3 cups daily after meals.', duration: '14 days', warnings: 'See a practitioner if symptoms persist beyond 2 weeks or if you lose weight unexpectedly.',
    contraindications: 'Avoid with gallstones unless advised by your practitioner.', pregnancy: 'Occasional use in pregnancy only on practitioner advice.',
    interactions: 'Ginger may increase the effect of blood thinners such as warfarin.', price: 3000, stock: 200, image: { hue: 45, shape: 'Tea bags' },
  });
  product('prd_prekese', 'org_nkabom', 'approved', {
    name: 'Prekese Aromatic Syrup', dosageForm: 'Syrup', packSize: '200 ml bottle', category: 'Nutrition & wellness', fdaRegNo: 'FDA/HD.23-1520', fdaExpiry: plusDays(280), manufacturer: 'Nkabom Herbal Clinic, Kumasi',
    ingredients: 'Tetrapleura tetraptera fruit extract 20%, honey 30%, purified water, citric acid, sodium benzoate 0.1%.', indication: 'Traditionally used as a general tonic.',
    directions: 'Adults: 10 ml twice daily. Shake well before use.', duration: '20 days', warnings: 'Contains honey: not for children under 1 year. Discard 60 days after opening.',
    contraindications: 'Avoid if you have diabetes unless advised, because of the honey content.', pregnancy: 'Not recommended during pregnancy.',
    interactions: 'No known interactions; tell your practitioner about other medicines you take.', price: 5500, stock: 40, image: { hue: 25, shape: 'Syrup' },
  });
  product('prd_neem', 'org_nkabom', 'approved', {
    name: 'Neem & Shea Skin Balm', dosageForm: 'Balm', packSize: '50 g tin', category: 'Topical preparations', fdaRegNo: 'FDA/HD.24-0321', fdaExpiry: plusDays(350), manufacturer: 'Nkabom Herbal Clinic, Kumasi',
    ingredients: 'Unrefined shea butter 70%, neem seed oil 10%, beeswax 15%, lemongrass oil 1%, vitamin E.', indication: 'Traditionally used to soothe dry, itchy skin.',
    directions: 'Apply a thin layer to clean skin twice daily. For external use only.', duration: '30 days', warnings: 'Do a patch test first. Stop if redness or irritation develops. Avoid broken skin and eyes.',
    contraindications: 'Do not use if allergic to neem, shea or beeswax.', pregnancy: 'Suitable for topical use; avoid applying to the breast area while breastfeeding.',
    interactions: 'None known for topical use.', price: 3500, stock: 4, pickup: true, image: { hue: 90, shape: 'Balm' },
  });
  product('prd_bitter', 'org_nkabom', 'approved', {
    name: 'Bitter Leaf Tincture', dosageForm: 'Tincture', packSize: '100 ml', category: 'Traditional herbal medicines', fdaRegNo: 'FDA/HD.21-0710', fdaExpiry: plusDays(-1), manufacturer: 'Nkabom Herbal Clinic, Kumasi',
    ingredients: 'Vernonia amygdalina leaf extract in 25% ethanol.', indication: 'Traditionally used to support digestion.', directions: '5 ml in water twice daily before meals.', duration: '14 days',
    warnings: 'Contains alcohol.', contraindications: 'Not for children, or people avoiding alcohol.', pregnancy: 'Do not use during pregnancy or breastfeeding.',
    interactions: 'May lower blood sugar; caution with diabetes medicines.', price: 4000, stock: 30, image: { hue: 140, shape: 'Tincture' },
  });
  product('prd_garlic', 'org_nkabom', 'submitted', {
    name: 'Garlic & Honey Mixture', dosageForm: 'Syrup', packSize: '250 ml bottle', category: 'Traditional herbal medicines', fdaRegNo: 'FDA/HD.25-0188', fdaExpiry: plusDays(700), manufacturer: 'Nkabom Herbal Clinic, Kumasi',
    ingredients: 'Allium sativum bulb extract 15%, honey 50%, ginger extract 5%, purified water.', indication: 'Traditionally used to soothe coughs and sore throats.', directions: 'Adults: 10 ml three times daily.', duration: '7 days',
    warnings: 'See a clinician if cough lasts more than 3 weeks or you cough up blood.', contraindications: 'Not for children under 1 year (honey).', pregnancy: 'Seek advice before use in pregnancy.',
    interactions: 'Garlic can increase bleeding risk with warfarin or aspirin.', price: 4800, stock: 60, image: { hue: 50, shape: 'Syrup' },
  });
  product('prd_sleep', 'org_nkabom', 'draft', {
    name: 'Sleep Calm Herbal Blend', dosageForm: 'Tea bags', packSize: '20 tea bags', category: 'Teas & infusions', fdaRegNo: 'FDA/HD.25-0402', fdaExpiry: plusDays(650), manufacturer: 'Nkabom Herbal Clinic, Kumasi',
    ingredients: 'Lemongrass, hibiscus, and Ocimum gratissimum leaf.', indication: 'Traditionally used to support relaxation before sleep.', directions: '1 cup 30 minutes before bed.', duration: '14 days',
    warnings: 'May cause drowsiness.', contraindications: 'Avoid with sedative medicines.', pregnancy: 'Seek advice before use.', interactions: 'May add to the effect of sleeping tablets.', price: 2800, stock: 50, image: { hue: 290, shape: 'Tea bags' },
  });
  product('prd_jointrub', 'org_nkabom', 'recalled', {
    name: 'Herbal Joint Rub', dosageForm: 'Balm', packSize: '60 g jar', category: 'Topical preparations', fdaRegNo: 'FDA/HD.22-1301', fdaExpiry: plusDays(120), manufacturer: 'Nkabom Herbal Clinic, Kumasi',
    ingredients: 'Shea butter, camphor 3%, eucalyptus oil 2%, wintergreen oil 1%.', indication: 'Traditionally used for temporary relief of muscle aches.', directions: 'Rub gently on the affected area up to 3 times daily.', duration: '14 days',
    warnings: 'External use only.', contraindications: 'Do not use on children under 6.', pregnancy: 'Avoid in pregnancy.', interactions: 'Wintergreen may increase the effect of warfarin.', price: 3800, stock: 0, image: { hue: 0, shape: 'Balm' },
    recall: { at: new Date(E.now() - 20 * D).toISOString(), reason: 'Microbial contamination found in batch NK-JR-0923', notified: 0 },
  });

  // ---------- education ----------
  const edu = [
    ['tip', 'Tell every practitioner about every medicine you take', 'Herbal products and prescription medicines can interact. Before any consultation, list what you take, including teas, tonics, vitamins and hospital medicines, and bring the packs if you can. Ginger, garlic and some bitters can change how blood thinners or diabetes medicines work.'],
    ['tip', 'When to go straight to hospital', 'Online and traditional consultations are not for emergencies. Call 112 or 193 for the National Ambulance Service, or go to the nearest emergency unit, for chest pain, difficulty breathing, heavy bleeding, fits, confusion, stroke signs or severe allergic reactions.'],
    ['medicine', 'Reading a herbal product label', 'Check for an FDA Ghana registration number, the manufacturer’s name and address, a full ingredient list, the dose, the expiry date and a batch number. Products without these details should not be used. Every product on PRORESMAT shows this information before you buy.'],
    ['medicine', 'Fever: test before you treat', 'Fever has many causes. Get a malaria test (RDT or microscopy) before using any fever remedy, herbal or conventional. Children with fever, stiff neck or drowsiness need urgent medical care.'],
    ['traditional', 'How traditional medicine is regulated in Ghana', 'The Traditional Medicine Practice Council (TMPC) registers and licenses traditional medicine practitioners and facilities. FDA Ghana registers herbal products. PRORESMAT checks both before a practitioner or product appears in the app.'],
    ['traditional', 'Medical herbalists and traditional practitioners', 'Medical herbalists complete a university degree in herbal medicine. Traditional medicine practitioners often train through apprenticeship and are licensed by TMPC. Both can advise on herbal treatments within their registered scope, and should refer you to a hospital when needed.'],
  ];
  edu.forEach(([category, title, body], i) => E.insert('education', { id: `edu_${i + 1}`, category, title, body, readMinutes: 2, publishedAt: new Date(E.now() - (i + 2) * D).toISOString() }));

  // ---------- history via real workflows ----------
  const at = (msFromRealNow) => { db.meta.clockOffsetMs = msFromRealNow; };
  const pay = async (u, purpose, targetId, channel = 'card') => {
    const init = await E.invoke('payments.initialize', { purpose, targetId, channel }, u);
    return E.invoke('payments.sandboxComplete', { reference: init.reference, outcome: 'success', card: '4084084084084081', provider: 'mtn', phone: u.phone }, u);
  };
  const consult = async (u, pracId, startMs, mode, reason, doc) => {
    at(startMs - 2 * D);
    const b = await E.invoke('bookings.create', { practitionerId: pracId, mode, start: new Date(E.now() + 2 * D).toISOString(), reason, screening: { redFlags: [], pregnancy: 'no', allergies: u.health?.allergies || '', currentMeds: u.health?.currentMeds || '' }, consent: true, policyAccepted: true }, u);
    await pay(u, 'booking', b.id, mode === 'video' ? 'card' : 'mobile_money');
    if (!doc) return b;
    const pUser = db.users[db.practitioners[pracId].userId];
    at(startMs + 5 * 60000);
    await E.invoke('consult.start', { id: b.id }, pUser);
    await E.invoke('consult.document', { id: b.id, ...doc.notes }, pUser);
    if (doc.plan) await E.invoke('consult.carePlan', { id: b.id, ...doc.plan }, pUser);
    at(startMs + 35 * 60000);
    await E.invoke('consult.complete', { id: b.id }, pUser);
    return b;
  };

  const realNow = 0;
  // 1) Completed consultation 20 days ago with Nana Kwame, settled 15 days ago.
  const b1 = await consult(kojo, 'prc_kwame', realNow - 20 * D + 10 * H, 'physical', 'Recurring knee pain after long walks, for about 3 months.', {
    notes: { presentingConcern: 'Bilateral knee pain after walking > 30 minutes, 3 months.', history: 'No trauma. No swelling or fever. Takes paracetamol occasionally.', assessment: 'Likely early osteoarthritic knee pain. No red flags.', plan: 'Weight-bearing exercise advice, warm compresses, review in 4 weeks. Referral for X-ray if not improving.', recommendation: 'Topical balm and lifestyle advice', rationale: 'Low-risk topical option; no interaction with paracetamol.' },
    plan: { type: 'care_plan', items: [{ productId: 'prd_neem', dosage: 'Thin layer', frequency: 'Twice daily', duration: '4 weeks', rationale: 'Soothing topical; avoid broken skin' }], advice: 'Walk 20 minutes daily on flat ground. Warm compress 10 minutes each evening. Return sooner if the knee swells, turns red or you cannot bear weight.', followUpDate: E.addDays(E.isoDate(Date.now()), -20 + 28) },
  });
  at(realNow - 15 * D);
  E.evaluateEarnings();
  await E.invoke('admin.runSettlement', {}, admin);

  // 2) Completed consultation 12 days ago with Ama (eligible for the next settlement run).
  const b2 = await consult(akosua, 'prc_ama', realNow - 12 * D + 11 * H, 'video', 'Low energy and poor appetite for the past month.', {
    notes: { presentingConcern: 'Fatigue and reduced appetite, 1 month.', history: 'Mild hypertension, monitored by GP; no current medicines. Penicillin allergy.', assessment: 'Fatigue likely related to poor diet and sleep. Advised full blood count at GP to exclude anaemia.', plan: 'Dietary plan, moringa supplement, sleep hygiene; review in 3 weeks.', recommendation: 'Moringa Leaf Capsules and dietary changes', rationale: 'Nutritional support; monitor blood pressure because moringa may lower it.' },
    plan: { type: 'care_plan', items: [{ productId: 'prd_moringa', dosage: '2 capsules', frequency: 'Twice daily after meals', duration: '30 days', rationale: 'Nutritional support' }, { productId: 'prd_ginger', dosage: '1 cup', frequency: 'After lunch and dinner', duration: '14 days', rationale: 'Appetite and digestion' }], advice: 'Eat three regular meals with leafy greens, beans and fish. Check your blood pressure weekly while taking moringa and stop if you feel dizzy. Get a full blood count at your GP.', followUpDate: E.addDays(E.isoDate(Date.now()), 9) },
  });
  // Moderated review of that consultation.
  at(realNow - 11 * D);
  const r1 = await E.invoke('reviews.create', { targetType: 'practitioner', bookingId: b2.id, rating: 5, text: 'Ama listened carefully, explained everything clearly and sent my care plan the same day.' }, akosua);
  await E.invoke('admin.moderateReview', { id: r1.id, status: 'published' }, admin);
  const r0 = await E.invoke('reviews.create', { targetType: 'practitioner', bookingId: b1.id, rating: 4, text: 'Nana Kwame was patient and gave practical advice. The clinic was easy to find.' }, kojo);
  await E.invoke('admin.moderateReview', { id: r0.id, status: 'published' }, admin);

  // 3) Order 10 days ago: PRORESMAT + Nkabom items, delivered 8 days ago.
  at(realNow - 10 * D);
  await E.invoke('cart.setItem', { productId: 'prd_moringa', qty: 1 }, akosua);
  await E.invoke('cart.setItem', { productId: 'prd_prekese', qty: 2 }, akosua);
  const chk = await E.invoke('checkout.create', { deliveryMethod: 'delivery', address: akosua.address, phone: akosua.phone, termsAccepted: true }, akosua);
  await pay(akosua, 'checkout', chk.checkoutId, 'mobile_money');
  const orderIds = db.checkouts[chk.checkoutId].orderIds;
  const [oStore, oClinic] = [orderIds.find((id) => db.orders[id].orgId === 'org_proresmat'), orderIds.find((id) => db.orders[id].orgId === 'org_nkabom')];
  const fulfil = async (oid, vendor, day0) => {
    at(day0 + 1 * H); await E.invoke('vendor.advanceOrder', { id: oid, status: 'accepted' }, vendor);
    at(day0 + 2 * H); await E.invoke('vendor.advanceOrder', { id: oid, status: 'stock_confirmed' }, vendor);
    const batches = Object.fromEntries(db.orders[oid].items.map((it, i) => [i, { batch: `${it.productId.slice(4, 7).toUpperCase()}-${2600 + i}`, expiry: E.addDays(E.today(), 400) }]));
    at(day0 + 4 * H); await E.invoke('vendor.advanceOrder', { id: oid, status: 'prepared', batches }, vendor);
    at(day0 + 6 * H); await E.invoke('vendor.advanceOrder', { id: oid, status: 'dispatched', note: 'Rider: Yaw (024 000 1111)' }, vendor);
    at(day0 + 1 * D + 3 * H); await E.invoke('vendor.advanceOrder', { id: oid, status: 'delivered', receivedBy: 'Akosua Mensah', note: 'Handed to customer' }, vendor);
  };
  await fulfil(oStore, uStore, realNow - 10 * D);
  await fulfil(oClinic, uClinic, realNow - 10 * D);
  at(realNow - 8 * D);
  await E.invoke('orders.acknowledge', { id: oClinic }, akosua);
  const r2 = await E.invoke('reviews.create', { targetType: 'org', orderId: oClinic, rating: 4, text: 'Well packed and delivered on time. This syrup cured my tiredness completely!' }, akosua);
  void r2; // stays pending: flagged for an efficacy claim so the moderator can see the rule in action

  // 4) Kojo's open clinic order from yesterday (awaiting acceptance).
  at(realNow - 1 * D);
  await E.invoke('cart.setItem', { productId: 'prd_neem', qty: 1 }, kojo);
  const chk2 = await E.invoke('checkout.create', { deliveryMethod: 'pickup', phone: kojo.phone, termsAccepted: true }, kojo);
  await pay(kojo, 'checkout', chk2.checkoutId, 'mobile_money');

  // 5) Red-flag screening that stopped a booking (goes to the care follow-up queue).
  at(realNow - 2 * D);
  try {
    await E.invoke('bookings.create', { practitionerId: 'prc_efua', mode: 'telephone', start: new Date(E.now() + D).toISOString(), reason: 'Sudden chest tightness when climbing stairs', screening: { redFlags: ['chest_pain'] }, consent: true, policyAccepted: true }, kojo);
  } catch { /* expected: RED_FLAG */ }

  // 6) Support ticket and privacy request.
  await E.invoke('tickets.create', { kind: 'support', category: 'delivery', subject: 'Can I change my pickup time?', message: 'I will only be able to collect my order on Saturday afternoon. Is that okay?', orderId: Object.values(db.orders).find((o) => o.customerId === kojo.id && o.status === 'received')?.id }, kojo);
  await E.invoke('privacy.request', { type: 'correction', details: 'My date of birth is recorded as 1984-11-02 but should be 1984-12-02.' }, kojo);
  await E.invoke('adverse.create', { kind: 'quality', severity: 'mild', productId: 'prd_ginger', description: 'Two tea bags in the pack were torn and the tea leaked into the box.' }, akosua);

  // 7) Upcoming consultations at real time.
  at(realNow);
  const next = E.nextAvailable(db.practitioners.prc_kofi);
  if (next) {
    const b = await E.invoke('bookings.create', { practitionerId: 'prc_kofi', mode: 'video', start: next, reason: 'Review of blood pressure while taking herbal supplements.', screening: { redFlags: [], pregnancy: 'no', allergies: 'Penicillin', currentMeds: 'Moringa Leaf Capsules' }, consent: true, policyAccepted: true, docIds: [] }, akosua);
    await pay(akosua, 'booking', b.id, 'card');
  }
  // A consultation that starts in 20 minutes so the practitioner flow can be tested immediately.
  const soon = await E.invoke('bookings.create', { practitionerId: 'prc_kwame', mode: 'telephone', start: new Date(Math.ceil((E.now() + 20 * 60000) / 60000) * 60000).toISOString(), reason: 'Follow-up: knee pain improving but still stiff in the mornings.', screening: { redFlags: [], pregnancy: 'not_applicable', allergies: '', currentMeds: 'Paracetamol as needed' }, consent: true, policyAccepted: true }, kojo);
  await pay(kojo, 'booking', soon.id, 'mobile_money');

  db.meta.clockOffsetMs = 0;
  // Keep only the most recent messages in the demo outbox.
  for (const m of Object.values(db.outbox)) if (Date.parse(m.at) < Date.now() - 3 * D) delete db.outbox[m.id];
  void newId;
}
